[2024-01-02T19:25:01.375+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion.transform_data scheduled__2024-01-01T19:23:53.566471+00:00 [queued]>
[2024-01-02T19:25:01.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion.transform_data scheduled__2024-01-01T19:23:53.566471+00:00 [queued]>
[2024-01-02T19:25:01.399+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-02T19:25:02.698+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform_data> on 2024-01-01 19:23:53.566471+00:00
[2024-01-02T19:25:02.827+0000] {standard_task_runner.py:57} INFO - Started process 2593 to run task
[2024-01-02T19:25:02.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'transform_data', 'scheduled__2024-01-01T19:23:53.566471+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_operator2.py', '--cfg-path', '/tmp/tmpc6qmlltg']
[2024-01-02T19:25:03.258+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask transform_data
[2024-01-02T19:25:03.753+0000] {task_command.py:415} INFO - Running <TaskInstance: booking_ingestion.transform_data scheduled__2024-01-01T19:23:53.566471+00:00 [running]> on host ce0bd5f35f4e
[2024-01-02T19:25:13.495+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='booking_ingestion' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T19:23:53.566471+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T19:23:53.566471+00:00'
[2024-01-02T19:25:26.418+0000] {logging_mixin.py:151} WARNING - /opt/***/dags/dag_with_postgress_operator2.py:46 UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
[2024-01-02T19:25:27.827+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgress_operator2.py", line 46, in transform_data
    data.booking_date = pd.to_datetime(data.booking_date, infer_datetime_format=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 1050, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 453, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 484, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
  File "pandas/_libs/tslibs/strptime.pyx", line 530, in pandas._libs.tslibs.strptime.array_strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 351, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "2017-10-17" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
[2024-01-02T19:25:28.592+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=transform_data, execution_date=20240101T192353, start_date=20240102T192501, end_date=20240102T192528
[2024-01-02T19:25:28.905+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task transform_data (time data "2017-10-17" doesn't match format "%Y/%m/%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.; 2593)
[2024-01-02T19:25:28.958+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T19:25:28.980+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
